# Generated by Django 6.0.2 on 2026-03-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.IntegerField(default=0, verbose_name='Tokens'),
        ),
    ]
